// <auto-generated />
using System;
using FineTracker.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FineTracker.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250808093334_Seeded Users")]
    partial class SeededUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FineTracker.Web.Models.Domain.FineModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Fines");
                });

            modelBuilder.Entity("FineTracker.Web.Models.Domain.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateJoined = new DateTime(2025, 8, 8, 15, 3, 33, 985, DateTimeKind.Local).AddTicks(3673),
                            Email = "dhruv.mehta@finova.tech",
                            IsActive = true,
                            UserName = "Dhruv"
                        },
                        new
                        {
                            Id = 2,
                            DateJoined = new DateTime(2025, 8, 8, 15, 3, 33, 985, DateTimeKind.Local).AddTicks(3674),
                            Email = "dhairya.sharma@finova.tech",
                            IsActive = true,
                            UserName = "Dhairya"
                        },
                        new
                        {
                            Id = 3,
                            DateJoined = new DateTime(2025, 8, 8, 15, 3, 33, 985, DateTimeKind.Local).AddTicks(3676),
                            Email = "tarun.gautam@finova.tech",
                            IsActive = true,
                            UserName = "Tarun"
                        },
                        new
                        {
                            Id = 4,
                            DateJoined = new DateTime(2025, 8, 8, 15, 3, 33, 985, DateTimeKind.Local).AddTicks(3677),
                            Email = "mukul.kumar@finova.tech",
                            IsActive = true,
                            UserName = "Mukul"
                        },
                        new
                        {
                            Id = 5,
                            DateJoined = new DateTime(2025, 8, 8, 15, 3, 33, 985, DateTimeKind.Local).AddTicks(3678),
                            Email = "gaurav.saini@finova.tech",
                            IsActive = true,
                            UserName = "Gaurav"
                        },
                        new
                        {
                            Id = 6,
                            DateJoined = new DateTime(2025, 8, 8, 15, 3, 33, 985, DateTimeKind.Local).AddTicks(3679),
                            Email = "shrawan.khatri@finova.tech",
                            IsActive = true,
                            UserName = "Shrawan"
                        });
                });

            modelBuilder.Entity("FineTracker.Web.Models.Domain.FineModel", b =>
                {
                    b.HasOne("FineTracker.Web.Models.Domain.UserModel", "User")
                        .WithMany("Fines")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FineTracker.Web.Models.Domain.UserModel", b =>
                {
                    b.Navigation("Fines");
                });
#pragma warning restore 612, 618
        }
    }
}
